---
title: "test_dsfinal"
author: "Wenshan Qu (wq2160)"
date: "12/3/2021"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(RCurl)
library(jsonlite)
```

Read data

```{r}
## 2021 data
fresh_df = 
  read_csv("./data/year_to_date.csv") %>% 
  janitor::clean_names() %>% 
  separate(occur_date, into = c("month", "day", "year"), sep = "/") %>% 
  mutate(
    year = as.integer(year),
    month = as.integer(month),
    day = as.integer(day),
    month = month.name[month] ## replace month number with month name 
  )

## Historical data --- Full version
history_full_df = 
  read_csv("./data/historic.csv") %>% 
  janitor::clean_names() %>% 
  separate(occur_date, into = c("month", "day", "year"), sep = "/") %>% 
  mutate(
    year = as.integer(year),
    month = as.integer(month),
    day = as.integer(day),
    month = month.name[month] ## replace month number with month name 
  )

## Historical data --- Filtered version, 2016 - 2020
history_filter_df = 
  read_csv("./data/historic.csv") %>% 
  janitor::clean_names() %>% 
  separate(occur_date, into = c("month", "day", "year"), sep = "/") %>% 
  mutate(
    year = as.integer(year),
    month = as.integer(month),
    day = as.integer(day),
    month = month.name[month] ## replace month number with month name 
  ) %>% 
  filter(year %in% c(2016:2020))
```

How to extract zipcode from geographical info

```{r function logic}
## This is the underlying logic of transforming lat-lon to zipcode

url = sprintf("http://nominatim.openstreetmap.org/reverse?format=json&lat=%f&lon=%f&zoom=18&addressdetails=1", 40.668262749000064, -73.89200350499993)
    
res = jsonlite::fromJSON(url)


## check result

res[["address"]][["postcode"]] ## extract address => postcode
```

Create Function

```{r}
latlon2zip = function(lat, lon) {
  
    url = sprintf("http://nominatim.openstreetmap.org/reverse?format=json&lat=%f&lon=%f&zoom=18&addressdetails=1", lat, lon)
    
    res = jsonlite::fromJSON(url)
    
    zipcode = 
      res[["address"]][["postcode"]] %>% 
      noquote() %>% 
      as.numeric()
    
    return(zipcode)
    
}

## test
latlon2zip(lat = 40.668262749000064, lon = -73.89200350499993)
## check running time
system.time(latlon2zip(lat = 40.668262749000064, lon = -73.89200350499993))
```

Use function in `filter df`

```{r}

## Check NA
na_situ = map_df(fresh_df, ~sum(is.na(.))) ## well done!

## Test with 8 rows: 4 sec
small_test = 
  fresh_df %>%
  filter(month == "June", day == "3") %>% 
  mutate(
    zip = map2(latitude, longitude, latlon2zip)
  )

## Check running time
system.time(
  fresh_df %>%
  filter(month == "June", day == "3") %>% 
  mutate(
    zip = map2(latitude, longitude, latlon2zip)
  )
)
```

On **2021 data**, formal zipcode generation.

```{r}
fresh_result = 
  fresh_df %>% 
  mutate(
    zipcode = map2(latitude, longitude, latlon2zip)
  )

fresh_result = 
  fresh_result %>% 
  mutate(
    zipcode = as.numeric(zipcode)
  )

write.csv(fresh_result, "./data/2021_with_zipcode.csv", row.names = FALSE)
```

**2020 data**:

```{r}
a_result =
  history_filter_df %>% 
  filter(year == "2020") %>% 
  mutate(
    zipcode = map2(latitude, longitude, latlon2zip)
  )

a_result = 
  a_result %>% 
  mutate(
    zipcode = as.numeric(zipcode)
  )

write.csv(a_result, "./data/2020_with_zipcode.csv", row.names = FALSE)  
```

**2019 data**

```{r}
b_result =
  history_filter_df %>% 
  filter(year == "2019") %>% 
  mutate(
    zipcode = map2(latitude, longitude, latlon2zip)
  )

b_result = 
  b_result %>% 
  mutate(
    zipcode = as.numeric(zipcode)
  )

write.csv(b_result, "./data/2019_with_zipcode.csv", row.names = FALSE) 
```

**2018 data**

```{r}
c_result =
  history_filter_df %>% 
  filter(year == "2018") %>% 
  mutate(
    zipcode = map2(latitude, longitude, latlon2zip)
  )

c_result = 
  c_result %>% 
  mutate(
    zipcode = as.numeric(zipcode)
  )

write.csv(c_result, "./data/2018_with_zipcode.csv", row.names = FALSE) 
```

**2017 data**

```{r}
d_result =
  history_filter_df %>% 
  filter(year == "2017") %>% 
  mutate(
    zipcode = map2(latitude, longitude, latlon2zip)
  )

d_result = 
  d_result %>% 
  mutate(
    zipcode = as.numeric(zipcode)
  )

write.csv(d_result, "./data/2017_with_zipcode.csv", row.names = FALSE) 
```

**2016 data**

```{r}
e_result =
  history_filter_df %>% 
  filter(year == "2016") %>% 
  mutate(
    zipcode = map2(latitude, longitude, latlon2zip)
  )

e_result = 
  e_result %>% 
  mutate(
    zipcode = as.numeric(zipcode)
  )

write.csv(e_result, "./data/2016_with_zipcode.csv", row.names = FALSE) 
```

Check for data

```{r}
data_2021 = read_csv("./data/2021_with_zipcode.csv")

na_2021 = map_df(data_2021, ~sum(is.na(.)))

data_2020 = read_csv("./data/2020_with_zipcode.csv")

na_2020 = map_df(data_2020, ~sum(is.na(.)))

data_2019 = read_csv("./data/2019_with_zipcode.csv")

na_2019 = map_df(data_2019, ~sum(is.na(.)))

data_2018 = read_csv("./data/2018_with_zipcode.csv")

na_2018 = map_df(data_2018, ~sum(is.na(.)))

data_2017 = read_csv("./data/2017_with_zipcode.csv")

na_2017 = map_df(data_2017, ~sum(is.na(.)))

data_2016 = read_csv("./data/2016_with_zipcode.csv")

na_2016 = map_df(data_2016, ~sum(is.na(.)))
```

#### Combine csv for 2016 - 2021

```{r}
library("dplyr")                                                
library("plyr")                                                 
library("readr")

full_data = list.files(path = "./modified_data",    
                       pattern = "*.csv", full.names = TRUE) %>% 
  lapply(read_csv) %>%                                           
  bind_rows   

full_data = 
  full_data %>% 
  janitor::clean_names() %>% 
  select(- x1)

## check NA
na_full = map_df(full_data, ~sum(is.na(.))) ## no lon and lat NA, 53 zipcode NA

write.csv(full_data, "./modified_data/NYC Shooting Data (2016-2021) with Zipcode.csv", row.names = FALSE)

```

**2015 data**

```{r}
f_result =
  history_full_df %>% 
  filter(year == "2015") %>% 
  mutate(
    zipcode = map2(latitude, longitude, latlon2zip)
  )

f_result = 
  f_result %>% 
  mutate(
    zipcode = as.numeric(zipcode)
  )

write.csv(f_result, "./data/2015_with_zipcode.csv", row.names = FALSE) 
```

**2014 data**

```{r}
g_result =
  history_full_df %>% 
  filter(year == "2014") %>% 
  mutate(
    zipcode = map2(latitude, longitude, latlon2zip)
  )

g_result = 
  g_result %>% 
  mutate(
    zipcode = as.numeric(zipcode)
  )

write.csv(g_result, "./data/2014_with_zipcode.csv", row.names = FALSE) 
```

**2013-2010 data**

```{r}
h_result =
  history_full_df %>% 
  filter(year %in% c(2010:2013)) %>% 
  mutate(
    zipcode = map2(latitude, longitude, latlon2zip)
  )

h_result = 
  h_result %>% 
  mutate(
    zipcode = as.numeric(zipcode)
  )

write.csv(h_result, "./data/2010_2013_with_zipcode.csv", row.names = FALSE) 
```

**2006-2009 data**

```{r}
i_result =
  history_full_df %>% 
  filter(year %in% c(2006:2009)) %>% 
  mutate(
    zipcode = map2(latitude, longitude, latlon2zip)
  )

i_result = 
  i_result %>% 
  mutate(
    zipcode = as.numeric(zipcode)
  )

write.csv(i_result, "./data/2006_2009_with_zipcode.csv", row.names = FALSE) 
```

Total data set (2006-2021) with zipcode

```{r}
total_data = list.files(path = "./comp_data",    
                       pattern = "*.csv", full.names = TRUE) %>% 
  lapply(read_csv) %>%                                           
  bind_rows %>% 
  janitor::clean_names()

write.csv(total_data, "./comp_data/Full NYC Shooting Data (2006-2021).csv", row.names = FALSE) 
```

```{r}
total = read_csv("./comp_data/Full NYC Shooting Data (2006-2021).csv") 

```

