---
title: "NYC shooting"
output: 
  flexdashboard::flex_dashboard:
    theme:
      version: 4 
      bootswatch: cosmo
    orientation: columns
    vertical_layout: fill
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(plotly)
library(leaflet)
library(maps)
library(rjson)
library(highcharter)
library(remotes)
```

```{r data import}
nyc_shooting = read_csv("./comp_data/Full NYC Shooting Data (2006-2021).csv")

nyc_time = 
  nyc_shooting %>% 
  separate(occur_time, into = c("hour", "minute", "second"), sep = ":") %>% 
  mutate(
    hour = as.factor(hour)
  )
```

Shooting Crime Finder
=====================================

Column {.sidebar}
-----------------------------------------------------------------------
### Find Shootings Near You

Interested in the life safety in New York City? Use our Shiny App to get ideas about the safe area and time with your zip-code! Our database includes over 20,000 data points on shooting incident cases in NYC from 2006 to 2021 (data source: NYPD). 

Please enter your zip-code of New York City (from 10001 to 11693) to get the distribution of shooting incidents, the safest month in a year, and the safest time in a day in your area.

```{r}
numericInput("zipcode", label = h4("Zipcode:"), 10032, min = 10001, max = 11693)
```

Column {data-width=600}
-----------------------------------------------------------------------

### NYC Shooting Incidents Map

```{r}
renderLeaflet({
  
nyc_shooting = 
  nyc_shooting %>% 
  filter(
    zipcode == input[["zipcode"]]
  ) 

risk_plot = 
  leaflet(data = nyc_shooting[]) %>% 
  setView(
    lng = mean(nyc_shooting$longitude),
    lat = mean(nyc_shooting$latitude), 
    zoom = 14
  ) %>% 
  addTiles() %>%
  addProviderTiles("Esri.WorldTopoMap") %>% 
  addCircleMarkers(
    ~ longitude,
    ~ latitude,
    radius = 5
  )

risk_plot
})
```

Column {data-width=400}
-----------------------------------------------------------------------

### The Safest Month in A Year?

```{r}
renderPlotly({
  
  dangerous_month = 
    nyc_shooting %>% 
      mutate(
        month = as.factor(month),
        month = fct_relevel(month, "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")
      ) %>% 
      filter(
        zipcode == input[["zipcode"]]
      ) %>% 
      dplyr::count(month) %>% 
      arrange(month) %>% 
      plot_ly(
        x = ~ month, y = ~ n, type = "bar", color = ~ month, colors = "viridis"
      ) %>% 
      layout(
        title = "Safest Month in Your Area", 
        xaxis = list(title = "Month"), 
        yaxis = list(title = "Number of Cases"),
        showlegend = FALSE
      )
  
  dangerous_month
  
})
```

### The Safest Time in A Day?

```{r}
renderPlotly({
  
  dangerous_time = 
    nyc_time %>% 
    filter(
        zipcode == input[["zipcode"]]
      ) %>% 
    dplyr::count(hour) %>% 
    arrange(hour) %>% 
    plot_ly(
      x = ~ hour, y = ~ n, type = "bar", color = ~ hour, colors = "viridis"
    ) %>% 
    layout(
      title = "Safest Hour in Your Area", 
      xaxis = list(title = "Hour"), 
      yaxis = list(title = "Number of Cases"),
      showlegend = FALSE
    )

  dangerous_time
  
})
```


Density Map
===================================== 

Column {.sidebar}
-----------------------------------------------------------------------
```{r}
year = c(2006:2021)

selectInput(
  "selected_year",
  label = h3("Select Interested Year"),  
  choices = as.list(year),
  selected = 2021
  )
```

Column
-----------------------------------------------------------------------

### Shooting Density Map

```{r}
renderHighchart({
  
  url1 = "https://data.beta.nyc/dataset/3bf5fb73-edb5-4b05-bb29-7c95f4a727fc/resource/6df127b1-6d04-4bb7-b983-07402a2c3f90/download/f4129d9aa6dd4281bc98d0f701629b76nyczipcodetabulationareas.geojson"
  nyczipgeojson = rjson::fromJSON(file = url1)

  zip_count = 
    nyc_shooting %>% 
    filter(year == input$selected_year) %>% 
    dplyr::count(zipcode)

  
  highchart() %>%
    hc_title(
      text = "NYC Shooting Density",
      style = list(fontSize = "24px", color = "#000000", fontWeight = "bold")
    ) %>%
    hc_subtitle(
      text = "by Zip-code",
      style = list(fontSize = "12px", color = "#000000", fontStyle = "italic")
    ) %>% 
    hc_add_series_map(nyczipgeojson, zip_count, 
      name = "Number of Shooting Cases:",
      value = "n", 
      joinBy = c("postalCode", "zipcode"),
      dataLabels = list(
        enabled = TRUE,
        format = "{point.properties.postalcode}"
        )
    ) %>% 
    hc_legend(
      valueDecimals = 0, 
      valueSuffix = "%",
      align = "right",
      verticalAlign = "top",
      layout = "vertical"
    ) %>%
    hc_mapNavigation(enabled = TRUE)

})
```

